import { User } from './user';
import { ObjectId, Document } from 'mongoose'; // Make sure to import Document from Mongoose

export interface Task extends Document {  // Extending Document makes sure the model works with Mongoose
  _id: ObjectId;  // `_id` should be of type `ObjectId` since it's generated by MongoDB
  name: string;
  status: 'todo' | 'inProgress' | 'done';
  createdAt: Date;
  _createdBy: ObjectId;  // _createdBy should be an ObjectId referencing a User
  projectId: ObjectId | null;  // Make sure to add `projectId` and it can be nullable if no project is assigned
  employees: Array<{
    employeeId: ObjectId | null;  // Reference to employee (nullable)
  }>;
}
